### ISSUE TITLE
[build] fail to build

### ISSUE THREAD

**Issue by LemonHX** [starcoinorg/starmask-extension#67]
```
❯ yarn install
yarn install v1.22.19
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @formatjs/intl-relativetimeformat > @formatjs/intl-utils@3.8.4: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
warning @metamask/controllers > eth-sig-util@3.0.1: Deprecated in favor of '@metamask/eth-sig-util'
warning @metamask/controllers > eth-keyring-controller > eth-sig-util@3.0.1: Deprecated in favor of '@metamask/eth-sig-util'
warning @metamask/controllers > ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update.
warning @metamask/controllers > eth-json-rpc-infura > eth-json-rpc-middleware > eth-sig-util@1.4.2: Deprecated in favor of '@metamask/eth-sig-util'
warning @metamask/controllers > web3-provider-engine > eth-sig-util@1.4.2: Deprecated in favor of '@metamask/eth-sig-util'
warning @metamask/controllers > babel-runtime > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning @metamask/controllers > eth-keyring-controller > eth-hd-keyring > eth-sig-util@3.0.1: Deprecated in favor of '@metamask/eth-sig-util'
warning @metamask/controllers > eth-keyring-controller > eth-simple-keyring > eth-sig-util@3.0.1: Deprecated in favor of '@metamask/eth-sig-util'
warning @metamask/controllers > eth-json-rpc-infura > json-rpc-engine > safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter   
warning @metamask/controllers > eth-json-rpc-infura > eth-json-rpc-middleware > safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
warning @metamask/controllers > eth-keyring-controller > obs-store > safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter      
warning @metamask/controllers > web3-provider-engine > ethereumjs-block@1.7.1: New package name format for new versions: @ethereumjs/block. Please update.
warning @metamask/controllers > web3-provider-engine > ethereumjs-block > ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update.
warning @metamask/controllers > web3-provider-engine > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @metamask/controllers > web3-provider-engine > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @metamask/controllers > web3-provider-engine > eth-block-tracker > safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
warning @metamask/controllers > web3-provider-engine > ethereumjs-vm@2.6.0: New package name format for new versions: @ethereumjs/vm. Please update.
warning @metamask/controllers > web3-provider-engine > ethereumjs-vm > ethereumjs-block@2.2.2: New package name format for new versions: @ethereumjs/block. Please update.
warning @metamask/controllers > web3-provider-engine > ethereumjs-vm > ethereumjs-block > ethereumjs-tx@2.1.2: New package name format for new versions: @ethereumjs/tx. Please update.
warning @metamask/controllers > web3-provider-engine > request > har-validator@5.1.5: this library is no longer supported
warning @metamask/controllers > web3-provider-engine > ethereumjs-vm > ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.
warning @metamask/controllers > web3-provider-engine > ethereumjs-vm > ethereumjs-block > ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.
warning @metamask/controllers > web3-provider-engine > ethereumjs-vm > ethereumjs-block > ethereumjs-tx > ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.   
warning @metamask/eth-ledger-bridge-keyring > eth-sig-util@1.4.2: Deprecated in favor of '@metamask/eth-sig-util'
warning @metamask/eth-ledger-bridge-keyring > ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update. 
warning @starcoin/stc-inpage-provider > webextension-polyfill-ts@0.25.0: This project has moved to @types/webextension-polyfill
warning @starcoin/stc-inpage-provider > extension-port-stream > webextension-polyfill-ts@0.22.0: This project has moved to @types/webextension-polyfill
warning @starcoin/stc-json-rpc-middleware > eth-sig-util@1.4.2: Deprecated in favor of '@metamask/eth-sig-util'
warning @starcoin/stc-json-rpc-middleware > safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
warning @starcoin/stc-keyring-controller > eth-sig-util@1.4.2: Deprecated in favor of '@metamask/eth-sig-util'
warning @starcoin/stc-keyring-controller > @starcoin/stc-util > noble-ed25519@1.2.6: Switch to namespaced @noble/ed25519 for security and feature updates
warning @starcoin/stc-keyring-controller > @starcoin/stc-simple-keyring > eth-sig-util@2.5.4: Deprecated in favor of '@metamask/eth-sig-util'
warning @starcoin/stc-keyring-controller > @starcoin/stc-hd-keyring > eth-sig-util@3.0.1: Deprecated in favor of '@metamask/eth-sig-util'   
warning @starcoin/stc-keyring-controller > @starcoin/stc-simple-keyring > @starcoin/stc-wallet > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @starcoin/stc-multisign-keyring > eth-sig-util@2.5.4: Deprecated in favor of '@metamask/eth-sig-util'
warning @starcoin/stc-onekey-keyring > eth-sig-util@1.4.2: Deprecated in favor of '@metamask/eth-sig-util'
warning @starcoin/stc-onekey-keyring > ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update.        
error Couldn't find package "@onekeyhq/connect@8.6.1" required by "@starcoin/stc-onekey-keyring@^1.1.1" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by LemonHX** [comment]
in linux
```
starmask-extension on  main via  v14.19.3 took 2m24s
❯ yarn dist
yarn run v1.22.19
$ yarn build prod
$ lavamoat development/build/index.js prod
(TypeError#1)

  TypeError#1: Cannot assign to read only property 'name' of function 'function createError(opts) {
          var result = new Error();

          Object.defineProperty(result, 'type', {...<omitted>... }'
           var result = new Error();

          Object.defineProperty(result, 'type', {...<omitted>... }'
    at extend (/home/lemonhx/js/starmask-extension/node_modules/xtend/mutable.js:12:29)
    at TypedError (/home/lemonhx/js/starmask-extension/node_modules/error/typed.js:26:5)
    at Object.eval (/home/lemonhx/js/starmask-extension/node_modules/body/any.js:10:28)
    at internalRequire (LavaMoat/core/kernel:353:25)
    at requireRelative (LavaMoat/core/kernel:394:27)
    at requireRelativeWithContext (LavaMoat/core/kernel:366:16)
    at Object.eval (/home/lemonhx/js/starmask-extension/node_modules/tiny-lr/src/server.js:36:12)
    at internalRequire (LavaMoat/core/kernel:353:25)
    at requireRelative (LavaMoat/core/kernel:394:27)
    at requireRelativeWithContext (LavaMoat/core/kernel:366:16)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
