### ISSUE TITLE
执行 `yarn setup:postinstall` 报错，sentry-cli 依赖安装失败

### ISSUE THREAD

**Issue by nangongamo** [starcoinorg/starmask-extension#83]
执行 `yarn setup:postinstall` 报错。
 
系统环境：windows 10
node 版本：v14.17.1

```
yarn setup:postinstall
yarn run v1.22.15
$ yarn patch-package && yarn allow-scripts
$ E:\code\study\github\starmask-extension\node_modules\.bin\patch-package
patch-package 6.4.7
Applying patches...
@reduxjs/toolkit@1.5.0 ✔
error@7.0.2 ✔
node-sass@4.14.1 ✔
plugin-error@1.0.1 ✔
regenerator-runtime@0.13.7 ✔
sass@1.32.4 ✔
stylelint@13.6.1 ✔
$ E:\code\study\github\starmask-extension\node_modules\.bin\allow-scripts
running lifecycle scripts for event "preinstall"
running lifecycle scripts for event "install"
- @sentry/cli
Error: command failed
    at ChildProcess.<anonymous> (E:\code\study\github\starmask-extension\node_modules\@npmcli\promise-spawn\index.js:64:27)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe',
  args: [ '/d', '/s', '/c', 'node scripts/install.js' ],
  code: 1,
  signal: null,
  stdout: '',
  stderr: 'Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/1.58.0/sentry-cli-Windows-x86_64.exe.\n' +
    'Error code: ECONNRESET\n',
  event: 'install',
  script: 'node scripts/install.js',
  pkgid: '@sentry/cli@1.58.0',
  path: 'node_modules\\@sentry\\cli'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by nangongamo** [comment]
解决办法：
执行如下命令：
`node ./node_modules/@sentry/cli/scripts/install.js`
等待下载 `sentry-cli-Windows-x86_64.exe` 完毕，
会在 `node_modules\@sentry\cli` 目录下生成个文件 `sentry-cli.exe` 就可以了。
重新执行：`yarn setup:postinstall`
