### ISSUE TITLE
执行 yarn start 报错

### ISSUE THREAD

**Issue by nangongamo** [starcoinorg/starmask-extension#84]
系统：Windows 10
Node版本：14.17.1
执行 `yarn start` 命令报错信息如下：
```
yarn start
yarn run v1.22.15
$ node development/build/index.js dev
running task "dev"...
Starting 'dev'...
Starting 'clean'...
Finished 'clean'
Starting 'styles:dev'...
Finished 'styles:dev'
Starting 'scripts:core:dev:background'...
Starting 'scripts:core:dev:ui'...
Starting 'scripts:core:dev:phishing-detect'...
Starting 'scripts:core:dev:initSentry'...
Starting 'scripts:core:dev:contentscript'...
Starting 'scripts:core:dev:disable-console'...
Starting 'static:dev'...
Starting 'manifest:dev'...
Starting 'reload'...
Finished 'reload'
Finished 'manifest:dev'
Finished 'static:dev'
scripts:core:dev:contentscript: (Error#1)
scripts:core:dev:contentscript:
scripts:core:dev:contentscript:   Error#1: LavaMoat - required package not in whitelist: package "@gulp-sourcemaps\map-sources" requested "through2" as "through2"
     at requireRelative (LavaMoat/core/kernel:414:15)
    at requireRelativeWithContext (LavaMoat/core/kernel:366:16)
    at Object.eval (E:\code\study\github\starmask-extension\node_modules\@gulp-sourcemaps\map-sources\index.js:4:15)
    at internalRequire (LavaMoat/core/kernel:353:25)
    at requireRelative (LavaMoat/core/kernel:394:27)
    at requireRelativeWithContext (LavaMoat/core/kernel:366:16)
    at Object.eval (E:\code\study\github\starmask-extension\node_modules\gulp-sourcemaps\index.js:7:15)
    at internalRequire (LavaMoat/core/kernel:353:25)
    at requireRelative (LavaMoat/core/kernel:394:27)
    at requireRelativeWithContext (LavaMoat/core/kernel:366:16)

scripts:core:dev:contentscript: error Command failed with exit code 1.
scripts:core:dev:contentscript: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
StarMask build: Encountered an error while running task "dev".
Error: StarMask build: runInChildProcess for task "scripts:core:dev:contentscript" encountered an error 1
    at ChildProcess.<anonymous> (E:\code\study\github\starmask-extension\development\build\task.js:89:13)
    at Object.onceWrapper (events.js:482:26)
    at ChildProcess.emit (events.js:375:28)
    at ChildProcess.emit (domain.js:470:12)
    at ChildProcess.cp.emit (E:\code\study\github\starmask-extension\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wk3368** [comment]
不好意思，只有mac，没有windows环境，没法重现。
